"""
morse_complex.py
================

Core library for computing complexes of discrete Morse matchings.

Provides routines to build simplicial complexes (the n-simplex, its boundary,
its skeleta, cones), construct their Hasse diagrams, enumerate (acyclic)
matchings, and assemble the complexes M(K), M_pure(K), and GM(K).

Conventions
-----------
- A simplex is a frozenset of vertex labels (typically integers).
- A simplicial complex is a frozenset of simplices, closed under taking faces.
- A Hasse covering pair (σ, τ) with σ ⊂ τ, dim τ = dim σ + 1, is represented
  as a frozenset {σ, τ} (so order is intrinsic from the dimensions).
- A matching is a frozenset of such pairs.
- A matching is "acyclic" if reversing the orientation of the matched edges
  in the Hasse diagram produces no directed cycle. Acyclic matchings on K
  are exactly the simplices of M(K). All matchings (acyclic or not) on K
  are the simplices of GM(K).
"""

from __future__ import annotations

from itertools import combinations
from typing import Iterable


# -------------------------------------------------------------------
# Simplicial complexes
# -------------------------------------------------------------------

Simplex = frozenset
Complex = frozenset  # frozenset of Simplex


def closure(simplices: Iterable[Iterable]) -> Complex:
    """Return the simplicial complex generated by `simplices`.

    Each input simplex contributes itself and all its non-empty faces.
    """
    K = set()
    for s in simplices:
        s = frozenset(s)
        # add all non-empty subsets
        for r in range(1, len(s) + 1):
            for face in combinations(s, r):
                K.add(frozenset(face))
    return frozenset(K)


def dim(K: Complex) -> int:
    """Return dim K = max dim of a simplex of K (or -1 if empty)."""
    if not K:
        return -1
    return max(len(s) for s in K) - 1


def simplex(n: int) -> Complex:
    """The standard n-simplex Δⁿ, with vertices {0, 1, ..., n}."""
    return closure([frozenset(range(n + 1))])


def boundary_simplex(n: int) -> Complex:
    """The boundary ∂Δⁿ of the standard n-simplex.

    All proper non-empty subsets of {0, 1, ..., n}.
    """
    K = simplex(n)
    top = frozenset(range(n + 1))
    return frozenset(s for s in K if s != top)


def skeleton(K: Complex, k: int) -> Complex:
    """The k-skeleton of K: all simplices of dimension ≤ k."""
    return frozenset(s for s in K if len(s) - 1 <= k)


def cone(K: Complex, apex_label) -> Complex:
    """The cone v * K with the given apex label.

    The apex must not appear as a vertex in K.
    """
    # check disjointness
    for s in K:
        if apex_label in s:
            raise ValueError(f"apex {apex_label} already a vertex of K")
    apex = frozenset([apex_label])
    new = set(K)
    new.add(apex)
    for s in K:
        new.add(s | apex)
    return frozenset(new)


def f_vector(K: Complex) -> tuple[int, ...]:
    """The f-vector (f_0, f_1, ..., f_d) where f_i = #simplices of dim i."""
    if not K:
        return ()
    d = dim(K)
    counts = [0] * (d + 1)
    for s in K:
        counts[len(s) - 1] += 1
    return tuple(counts)


def euler_characteristic(K: Complex) -> int:
    """χ(K) = Σ (-1)^i f_i."""
    return sum((-1) ** i * fi for i, fi in enumerate(f_vector(K)))


# -------------------------------------------------------------------
# Hasse diagram
# -------------------------------------------------------------------

def hasse_pairs(K: Complex) -> frozenset:
    """All Hasse covering pairs of K.

    Returned as a frozenset of frozensets {σ, τ}, one for each
    σ ⊂ τ with dim τ = dim σ + 1.
    """
    # bucket simplices by dimension for efficient enumeration
    by_dim: dict[int, list[Simplex]] = {}
    for s in K:
        by_dim.setdefault(len(s) - 1, []).append(s)

    pairs = set()
    for d, lower in by_dim.items():
        upper = by_dim.get(d + 1, [])
        for sigma in lower:
            for tau in upper:
                if sigma < tau:
                    pairs.add(frozenset([sigma, tau]))
    return frozenset(pairs)


def lower(pair) -> Simplex:
    """Given a covering pair {σ, τ}, return σ (the lower-dim element)."""
    a, b = tuple(pair)
    return a if len(a) < len(b) else b


def upper(pair) -> Simplex:
    """Given a covering pair {σ, τ}, return τ (the higher-dim element)."""
    a, b = tuple(pair)
    return a if len(a) > len(b) else b


def is_matching(pairs: Iterable) -> bool:
    """A set of Hasse pairs is a matching iff no simplex appears in two pairs."""
    seen = set()
    for p in pairs:
        for s in p:
            if s in seen:
                return False
            seen.add(s)
    return True


def is_acyclic(K: Complex, matching: Iterable) -> bool:
    """Test acyclicity of the matching (a set of Hasse pairs in K).

    Build the modified Hasse diagram and check for directed cycles.
    Modified: matched edges go upward (σ → τ if (σ,τ) is matched);
    unmatched Hasse edges go downward (τ → σ if σ ⊂ τ unmatched).
    """
    matching = frozenset(matching)
    matched_set = set()
    for p in matching:
        matched_set.add(p)

    # build adjacency: for each simplex, list of out-neighbors
    adj: dict[Simplex, list[Simplex]] = {s: [] for s in K}

    all_pairs = hasse_pairs(K)
    for p in all_pairs:
        sigma, tau = lower(p), upper(p)
        if p in matched_set:
            adj[sigma].append(tau)  # matched: σ → τ (upward)
        else:
            adj[tau].append(sigma)  # unmatched: τ → σ (downward)

    # cycle detection via DFS with three-color marking
    WHITE, GRAY, BLACK = 0, 1, 2
    color: dict[Simplex, int] = {s: WHITE for s in K}

    def has_cycle_from(v: Simplex) -> bool:
        # iterative DFS to avoid recursion limits
        stack = [(v, iter(adj[v]))]
        color[v] = GRAY
        while stack:
            node, it = stack[-1]
            try:
                w = next(it)
                if color[w] == GRAY:
                    return True
                if color[w] == WHITE:
                    color[w] = GRAY
                    stack.append((w, iter(adj[w])))
            except StopIteration:
                color[node] = BLACK
                stack.pop()
        return False

    for s in K:
        if color[s] == WHITE:
            if has_cycle_from(s):
                return False
    return True


# -------------------------------------------------------------------
# Enumeration of matchings (acyclic and not)
# -------------------------------------------------------------------

def all_matchings(K: Complex):
    """Generate every matching on the Hasse diagram of K (no acyclicity).

    Includes the empty matching. Useful for GM(K).
    """
    pairs = sorted(hasse_pairs(K), key=_pair_sort_key)
    yield from _extend_matching(pairs, frozenset(), set(), 0)


def _pair_sort_key(p):
    """A stable sort key for Hasse pairs that works with heterogeneous vertex types."""
    return tuple(sorted((tuple(sorted(map(repr, s))) for s in p)))


def _extend_matching(pairs: list, current: frozenset, used: set, idx: int):
    """Recursive helper: extend `current` by considering `pairs[idx:]`."""
    yield current
    for i in range(idx, len(pairs)):
        p = pairs[i]
        if any(s in used for s in p):
            continue
        new_used = used | set(p)
        yield from _extend_matching(pairs, current | {p}, new_used, i + 1)


def all_acyclic_matchings(K: Complex):
    """Generate every acyclic matching on the Hasse diagram of K.

    Includes the empty matching. Each yielded matching is a frozenset of
    Hasse covering pairs.
    """
    pairs = sorted(hasse_pairs(K), key=_pair_sort_key)
    yield from _extend_acyclic(K, pairs, frozenset(), set(), 0)


def _extend_acyclic(K, pairs, current, used, idx):
    yield current
    for i in range(idx, len(pairs)):
        p = pairs[i]
        if any(s in used for s in p):
            continue
        new_match = current | {p}
        if not is_acyclic(K, new_match):
            continue
        yield from _extend_acyclic(K, pairs, new_match, used | set(p), i + 1)


def maximal_acyclic_matchings(K: Complex):
    """Generate the maximal acyclic matchings on K (i.e. the top facets of M(K)).

    A matching is maximal if no Hasse pair can be added while preserving
    acyclicity. We enumerate all acyclic matchings and yield those that
    are maximal.

    For larger K this should be replaced by a branch-and-bound that prunes
    early; the naïve filter is fine for K of size we test here.
    """
    matchings = list(all_acyclic_matchings(K))
    for m in matchings:
        is_max = True
        used = set()
        for p in m:
            for s in p:
                used.add(s)
        for p in hasse_pairs(K):
            if any(s in used for s in p):
                continue
            # can we extend?
            if is_acyclic(K, m | {p}):
                is_max = False
                break
        if is_max:
            yield m


def optimal_matchings(K: Complex):
    """Generate the optimal acyclic matchings on K, i.e. those of maximum size.

    For Δⁿ and similar, optimal = maximal because Δⁿ is collapsible. For
    general K, an optimal matching is one with the minimum number of critical
    cells (equivalently maximum number of matched pairs); this equals the
    maximum acyclic matching size.
    """
    # First, find the max size by walking acyclic matchings.
    max_size = 0
    cache = []
    for m in all_acyclic_matchings(K):
        if len(m) > max_size:
            max_size = len(m)
            cache = [m]
        elif len(m) == max_size:
            cache.append(m)
    yield from cache


# -------------------------------------------------------------------
# The complexes M(K), M_pure(K), GM(K)
# -------------------------------------------------------------------

def morse_complex(K: Complex) -> Complex:
    """The complex M(K) of acyclic matchings on K.

    Vertices of M(K) are the non-empty primitive gradient vector fields,
    i.e. the Hasse pairs of K. Simplices are the non-empty acyclic matchings.

    Returned as a simplicial complex whose simplices are frozensets of
    Hasse pairs.
    """
    simplices = []
    for m in all_acyclic_matchings(K):
        if m:  # non-empty
            simplices.append(m)
    # The k-simplices are matchings of size k+1. The complex is closed under
    # face: if m is acyclic, every subset of m is acyclic (acyclicity is a
    # downward-closed property on matchings).
    return frozenset(simplices)


def gm_complex(K: Complex) -> Complex:
    """The generalized Morse complex GM(K) of all matchings on K (no acyclicity)."""
    simplices = []
    for m in all_matchings(K):
        if m:
            simplices.append(m)
    return frozenset(simplices)


def morse_complex_pure(K: Complex) -> Complex:
    """The pure Morse complex M_pure(K), generated by the optimal matchings.

    M_pure(K) is the subcomplex of M(K) generated by the matchings of
    maximum size; equivalently, it's the closure of the top-dimensional
    facets of M(K).
    """
    optimals = list(optimal_matchings(K))
    if not optimals:
        return frozenset()
    # Generate the closure: every non-empty subset of every optimal matching.
    simplices = set()
    for m in optimals:
        ms = list(m)
        for r in range(1, len(ms) + 1):
            for sub in combinations(ms, r):
                simplices.add(frozenset(sub))
    return frozenset(simplices)
